apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: stateful-app
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
     name: mysql-pvc
    spec:
      storageClassName: faster
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi




          
